### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by amitlals** [tylerprogramming/ai#2]
Hi ,
I tried exact code, seems nothing happening with next prompt, 

--------------------------------------------------------------------------------
Provide feedback to chat_manager. Press enter to skip and use auto-reply, or type 'exit' to end the conversation:

>>>>>>>> NO HUMAN INPUT RECEIVED.

>>>>>>>> USING AUTO REPLY...
ProjMara (to chat_manager):

--------------------------------------------------------------------------------
Provide feedback to chat_manager. Press enter to skip and use auto-reply, or type 'exit' to end the conversation:

**Comment by tylerprogramming** [comment]
Hey @amitlals which project are you having issue with?

**Comment by tylerprogramming** [comment]
Okay thank you!  By default I had it set to use gpt-3.5-turbo, which doesn't always give you the best results.  But if you were getting something like this:

Provide feedback to chat_manager. Press enter to skip and use auto-reply, or type 'exit' to end the conversation: 

>>>>>>>> NO HUMAN INPUT RECEIVED.

>>>>>>>> USING AUTO REPLY...
Admin (to chat_manager):



--------------------------------------------------------------------------------


Initially the Admin will have a chat with the chat manager which is the prompt from the initiate_chat function.  After that, The admin is you, so unless you want to say something for the agents to update and/or change then you would type it.  If not, then when you hit Enter, it will be blank.  

I'm going to push a small update where you don't have to reply, it will happen by default with '...'.  You will see in the code that I set the human_input_mode to 'NEVER', and I set a default auto-reply.  You can change this of course to what it was, but this may help.  I tested again and I switched the model to gpt-4 and on the first try it gave me something I wanted.

With 3.5-turbo it may take a couple tries to get a python file you like or works.  But it should be okay.  Test this out and let me know!

**Comment by amitlals** [comment]
Thank you for your inputs. I'm seeing bit strange behavior seeing in your YT demo, I see each persona planner, engineer, critic showing some bullet points, in my case directly executor showing the code that' bit surprising to me here, why its skipping to executor directly w.o consulting other personas
I'm using latest gpt-4-1106-preview btw. 

![image](https://github.com/tylerprogramming/ai/assets/37605691/15f3c5ce-ed90-4449-ad8e-e7c1de37b95b)

**Comment by amitlals** [comment]
Not sure if autogen can run the entire codebase autonomously even if we switch to NEVER ?

**Comment by tylerprogramming** [comment]
Older issue, code updates since then
